### PR TITLE
Add semicolons to class properties (babel spec compliance fixes)

### PR DESCRIPTION
**Pull request by sczk**
**Problem**: On a fresh Meteor 1.2.1 install after cloning the repository I received the following errors when trying to run the project:

`“ERROR in {PATH} Module build failed: SyntaxError: {FILE_NAME}: A semicolon is required after a class property (#:#)”`

**Proposed Fix**: Semicolons are added to any class properties that were missing them.

**More Information**: It looks like the change to babel that enforces this spec change is here: https://github.com/babel/babel/pull/3225

### CODE REVIEW

**Comment by zaklampert** [comment]
+1

**Comment by flying-sheep** [comment]
since [6.5.2](https://github.com/babel/babel/releases/tag/v6.5.2) this is unneeded

**Comment by sczk** [comment]
@flying-sheep Awesome! Thanks for the update.

**Comment by eXon** [comment]
Yea I learned that after migrating every major projects at work. Thanks for caring :)

**Pull request closed without merging**
